import Head from 'next/head'
import Link from 'next/link'
import { useState, useEffect } from 'react';

import { trpc } from '@/utils/trpc'

export default function Home() {
  const hello = trpc.hello.useQuery({ text: "cliente" });
  const ping = trpc.pong.useQuery("luwol")


  return (
    <>
      <Head>
        <title>NonFreeman</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div >
          <h1 className='text-3xl underline'>hola</h1>
        </div>
        <div>
          <p>{hello.data?.greeting}</p>
          <p>{ping.data?.pongRes}</p>
        </div>
      </main>
    </>
  )
}
